#!/bin/bash
#
# CleanData CRM - One-Command Installer
# Usage: curl -fsSL https://install.cleandata.app | bash
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print with colors
print_status() {
    echo -e "${BLUE}ℹ${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Print banner
clear
echo "╔══════════════════════════════════════════════════════════╗"
echo "║                                                          ║"
echo "║           🚀 CleanData CRM Installer                     ║"
echo "║                                                          ║"
echo "║   One-command installation for non-technical users      ║"
echo "║                                                          ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# Check prerequisites
print_status "Checking prerequisites..."

if ! command_exists docker; then
    print_error "Docker is not installed"
    echo ""
    echo "Please install Docker first:"
    echo "  Ubuntu/Debian: sudo apt-get install docker.io docker-compose"
    echo "  macOS: brew install docker"
    echo "  Windows: https://docs.docker.com/desktop/install/windows-install/"
    exit 1
fi

if ! command_exists docker-compose; then
    print_error "Docker Compose is not installed"
    echo "It usually comes with Docker Desktop"
    exit 1
fi

print_success "Docker is installed"

# Create installation directory
INSTALL_DIR="$HOME/cleandata-crm"
print_status "Creating installation directory: $INSTALL_DIR"

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Download docker-compose.yml
print_status "Downloading application files..."

curl -fsSL https://raw.githubusercontent.com/cleandata/crm/main/docker-compose.yml -o docker-compose.yml
curl -fsSL https://raw.githubusercontent.com/cleandata/crm/main/.env.example -o .env.example

print_success "Files downloaded"

# Interactive configuration
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Configuration Setup (Press Enter to accept defaults)"
echo "═══════════════════════════════════════════════════════════"
echo ""

# Function to prompt for input
prompt_input() {
    local prompt="$1"
    local default="$2"
    local var_name="$3"
    
    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " input
        input="${input:-$default}"
    else
        read -p "$prompt: " input
    fi
    
    eval "$var_name='$input'"
}

# Collect configuration
prompt_input "Application Domain" "localhost:3000" "APP_DOMAIN"
prompt_input "Admin Email" "" "ADMIN_EMAIL"
prompt_input "Company Name" "My Company" "COMPANY_NAME"

echo ""
print_status "Database: Using SQLite (no setup required)"
print_status "Cache: Using in-memory (no Redis required)"
print_status "Email: Using console log (no email provider required)"

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Optional: Connect External Services"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "You can skip these and add them later in Settings"
echo ""

read -p "Connect Salesforce now? (y/N): " connect_salesforce
if [[ $connect_salesforce =~ ^[Yy]$ ]]; then
    echo ""
    echo "1. Go to: https://login.salesforce.com"
    echo "2. Setup → App Manager → New Connected App"
    echo "3. Enable OAuth, set callback: http://$APP_DOMAIN/api/auth/salesforce/callback"
    echo ""
    prompt_input "Salesforce Client ID" "" "SALESFORCE_CLIENT_ID"
    prompt_input "Salesforce Client Secret" "" "SALESFORCE_CLIENT_SECRET"
fi

read -p "Connect Stripe for billing? (y/N): " connect_stripe
if [[ $connect_stripe =~ ^[Yy]$ ]]; then
    echo ""
    echo "1. Go to: https://dashboard.stripe.com/apikeys"
    echo "2. Copy your Secret key"
    echo ""
    prompt_input "Stripe Secret Key (sk_...)" "" "STRIPE_SECRET_KEY"
    prompt_input "Stripe Publishable Key (pk_...)" "" "STRIPE_PUBLISHABLE_KEY"
fi

# Generate secrets
NEXTAUTH_SECRET=$(openssl rand -base64 32)

# Create .env file
print_status "Creating configuration file..."

cat > .env << EOF
# Auto-generated by CleanData CRM Installer
# Generated: $(date)

# Application
NEXT_PUBLIC_APP_URL="http://$APP_DOMAIN"
NEXT_PUBLIC_APP_NAME="$COMPANY_NAME - CRM"
NODE_ENV="production"
PORT=3000

# Security
NEXTAUTH_SECRET="$NEXTAUTH_SECRET"

# Database (SQLite - zero config)
DATABASE_URL="file:./data/crm.db"

# Cache (In-memory - zero config)
REDIS_URL="memory"

# Email (Console log - zero config)
EMAIL_PROVIDER="console"

# Optional: Salesforce
SALESFORCE_CLIENT_ID="${SALESFORCE_CLIENT_ID:-}"
SALESFORCE_CLIENT_SECRET="${SALESFORCE_CLIENT_SECRET:-}"
SALESFORCE_REDIRECT_URI="http://$APP_DOMAIN/api/auth/salesforce/callback"

# Optional: Stripe
STRIPE_SECRET_KEY="${STRIPE_SECRET_KEY:-}"
STRIPE_PUBLISHABLE_KEY="${STRIPE_PUBLISHABLE_KEY:-}"
STRIPE_WEBHOOK_SECRET=""
EOF

print_success "Configuration saved"

# Create data directory
mkdir -p data

# Start application
print_status "Starting CleanData CRM..."
echo "This may take 2-3 minutes on first run..."
echo ""

docker-compose up -d

# Wait for startup
print_status "Waiting for application to start..."
sleep 10

# Check if running
if docker-compose ps | grep -q "Up"; then
    print_success "Application is running!"
    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo "  🎉 Installation Complete!"
    echo "═══════════════════════════════════════════════════════════"
    echo ""
    echo "Your CRM is ready at:"
    echo "  → http://$APP_DOMAIN"
    echo ""
    echo "Default login:"
    echo "  → Email: $ADMIN_EMAIL"
    echo "  → Password: (set on first login)"
    echo ""
    echo "Next steps:"
    echo "  1. Visit http://$APP_DOMAIN/signup to create admin account"
    echo "  2. Connect Salesforce in Settings"
    echo "  3. Import your contacts"
    echo ""
    echo "Useful commands:"
    echo "  View logs:  docker-compose logs -f"
    echo "  Stop:       docker-compose stop"
    echo "  Start:      docker-compose start"
    echo "  Update:     docker-compose pull && docker-compose up -d"
    echo ""
    echo "Need help? support@cleandata.app"
    echo ""
else
    print_error "Application failed to start"
    echo ""
    echo "Check logs with: docker-compose logs"
    exit 1
fi